require('dotenv').config();

const express = require('express');
const oracledb = require('oracledb');
const jwt = require('jsonwebtoken');

const app = express();
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET;
const ACCESS_TOKEN_TTL = process.env.ACCESS_TOKEN_TTL || '2m';
const REFRESH_TOKEN_TTL = process.env.REFRESH_TOKEN_TTL || '7d';
const AUTH_USER = process.env.AUTH_USER || 'demo-user';
const AUTH_PASSWORD = process.env.AUTH_PASSWORD || 'demo-password';

if (!JWT_SECRET) {
  throw new Error('JWT_SECRET debe configurarse en backend/.env');
}

app.use(express.json());

function issueTokens(userId) {
  return {
    accessToken: jwt.sign({ sub: userId, type: 'access' }, JWT_SECRET, { expiresIn: ACCESS_TOKEN_TTL }),
    refreshToken: jwt.sign({ sub: userId, type: 'refresh' }, JWT_SECRET, { expiresIn: REFRESH_TOKEN_TTL })
  };
}

function requireAuth(req, res, next) {
  const header = req.get('Authorization') || '';
  const token = header.startsWith('Bearer ') ? header.slice(7) : null;
  if (!token) return res.status(401).json({ success: false, message: 'Sesión no autorizada' });
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    if (payload.type !== 'access') throw new Error('Tipo de token inválido');
    req.userId = String(payload.sub);
    next();
  } catch (_) {
    return res.status(401).json({ success: false, message: 'Sesión expirada' });
  }
}

app.post('/api/auth/login', (req, res) => {
  const { username, password } = req.body || {};
  if (!username || !password) {
    return res.status(422).json({ success: false, message: 'Error de validación', errors: {
      username: 'El usuario es obligatorio', password: 'La contraseña es obligatoria'
    } });
  }
  if (username !== AUTH_USER || password !== AUTH_PASSWORD) {
    return res.status(401).json({ success: false, message: 'Credenciales inválidas' });
  }
  return res.json({ success: true, userId: AUTH_USER, ...issueTokens(AUTH_USER) });
});

app.post('/api/auth/refresh', (req, res) => {
  const { refreshToken } = req.body || {};
  if (!refreshToken) return res.status(401).json({ success: false, message: 'Refresh token requerido' });
  try {
    const payload = jwt.verify(refreshToken, JWT_SECRET);
    if (payload.type !== 'refresh') throw new Error('Tipo de token inválido');
    return res.json({ success: true, userId: String(payload.sub), ...issueTokens(String(payload.sub)) });
  } catch (_) {
    return res.status(401).json({ success: false, message: 'Refresh token inválido o expirado' });
  }
});

async function ensureExpensesTable(connection) {
  try {
    await connection.execute(`
      CREATE TABLE CC_GASTOS_SYNC (
        ID_GASTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        CLIENT_OPERATION_ID VARCHAR2(100) NOT NULL UNIQUE,
        USER_ID VARCHAR2(100) NOT NULL,
        CATEGORY_ID VARCHAR2(100) NOT NULL,
        AMOUNT NUMBER(12,2) NOT NULL,
        DESCRIPTION VARCHAR2(255) NOT NULL,
        EXPENSE_DATE TIMESTAMP NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    `);
  } catch (error) {
    if (error.errorNum !== 955) throw error;
  }
}

function expenseFromRow(row) {
  return {
    server_id: row.ID_GASTO,
    client_operation_id: row.CLIENT_OPERATION_ID,
    user_id: row.USER_ID,
    category_id: row.CATEGORY_ID,
    amount: row.AMOUNT,
    description: row.DESCRIPTION,
    date: row.EXPENSE_DATE.toISOString(),
    created_at: row.CREATED_AT.toISOString(),
    updated_at: row.UPDATED_AT.toISOString()
  };
}

app.get('/api/gastos', requireAuth, async (req, res) => {
  let connection;
  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });
    await ensureExpensesTable(connection);
    const result = await connection.execute(
      `SELECT * FROM CC_GASTOS_SYNC WHERE USER_ID = :userId ORDER BY EXPENSE_DATE DESC`,
      { userId: req.userId },
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    res.json({ success: true, data: result.rows.map(expenseFromRow) });
  } catch (error) {
    console.error('Error al listar gastos:', error.message);
    res.status(500).json({ success: false, message: 'No fue posible listar los gastos' });
  } finally {
    if (connection) await connection.close();
  }
});

app.post('/api/gastos', requireAuth, async (req, res) => {
  let connection;
  const { client_operation_id: operationId, user_id: userId, category_id: categoryId,
    amount, description, date, updated_at: updatedAt } = req.body;
  if (userId !== req.userId || !operationId || !categoryId || typeof amount !== 'number' || amount <= 0 || !date || !updatedAt || !String(description || '').trim()) {
    return res.status(422).json({ success: false, message: 'Error de validación', errors: {
      amount: typeof amount !== 'number' || amount <= 0 ? 'El monto debe ser mayor que 0' : undefined,
      description: !String(description || '').trim() ? 'La descripción es obligatoria' : undefined
    } });
  }
  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });
    await ensureExpensesTable(connection);
    await connection.execute(`
      MERGE INTO CC_GASTOS_SYNC target
      USING (SELECT :operationId client_operation_id FROM dual) source
      ON (target.CLIENT_OPERATION_ID = source.client_operation_id)
      WHEN MATCHED THEN UPDATE SET
        target.USER_ID = :userId,
        target.CATEGORY_ID = :categoryId,
        target.AMOUNT = :amount,
        target.DESCRIPTION = :description,
        target.EXPENSE_DATE = :expenseDate,
        target.UPDATED_AT = :updatedAt
        WHERE target.UPDATED_AT < :updatedAt
      WHEN NOT MATCHED THEN INSERT
        (CLIENT_OPERATION_ID, USER_ID, CATEGORY_ID, AMOUNT, DESCRIPTION, EXPENSE_DATE, UPDATED_AT)
        VALUES (:operationId, :userId, :categoryId, :amount, :description,
          :expenseDate, :updatedAt)
    `, { operationId, userId: String(userId), categoryId: String(categoryId), amount,
      description: description || '', expenseDate: new Date(date), updatedAt: new Date(updatedAt) }, { autoCommit: true });
    const result = await connection.execute(
      `SELECT * FROM CC_GASTOS_SYNC WHERE CLIENT_OPERATION_ID = :operationId`,
      { operationId }, { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    res.status(200).json({ success: true, data: expenseFromRow(result.rows[0]) });
  } catch (error) {
    console.error('Error al sincronizar gasto:', error.message);
    res.status(500).json({ success: false, message: 'No fue posible sincronizar el gasto' });
  } finally {
    if (connection) await connection.close();
  }
});

app.get('/api/health', async (req, res) => {
  let connection;

  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });

    const result = await connection.execute(
      `SELECT 'CONNECTED' AS STATUS FROM DUAL`
    );

    res.status(200).json({
      success: true,
      message: 'API de CashControl funcionando correctamente',
      database: result.rows[0][0]
    });
  } catch (error) {
    console.error('Error de conexión con Oracle:', error.message);

    res.status(500).json({
      success: false,
      message: 'La API está funcionando, pero no fue posible conectar con Oracle'
    });
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (error) {
        console.error('Error al cerrar la conexión:', error.message);
      }
    }
  }
});

app.listen(PORT, () => {
  console.log(`Servidor CashControl ejecutándose en http://localhost:${PORT}`);
});