require('dotenv').config();

const express = require('express');
const oracledb = require('oracledb');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

async function ensureExpensesTable(connection) {
  try {
    await connection.execute(`
      CREATE TABLE CC_GASTOS_SYNC (
        ID_GASTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        CLIENT_OPERATION_ID VARCHAR2(100) NOT NULL UNIQUE,
        USER_ID VARCHAR2(100) NOT NULL,
        CATEGORY_ID VARCHAR2(100) NOT NULL,
        AMOUNT NUMBER(12,2) NOT NULL,
        DESCRIPTION VARCHAR2(255) NOT NULL,
        EXPENSE_DATE TIMESTAMP NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    `);
  } catch (error) {
    if (error.errorNum !== 955) throw error;
  }
}

function expenseFromRow(row) {
  return {
    server_id: row.ID_GASTO,
    client_operation_id: row.CLIENT_OPERATION_ID,
    user_id: row.USER_ID,
    category_id: row.CATEGORY_ID,
    amount: row.AMOUNT,
    description: row.DESCRIPTION,
    date: row.EXPENSE_DATE.toISOString(),
    created_at: row.CREATED_AT.toISOString(),
    updated_at: row.UPDATED_AT.toISOString()
  };
}

app.get('/api/gastos', async (req, res) => {
  let connection;
  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });
    await ensureExpensesTable(connection);
    const result = await connection.execute(
      `SELECT * FROM CC_GASTOS_SYNC WHERE USER_ID = :userId ORDER BY EXPENSE_DATE DESC`,
      { userId: String(req.query.user_id || '') },
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    res.json({ success: true, data: result.rows.map(expenseFromRow) });
  } catch (error) {
    console.error('Error al listar gastos:', error.message);
    res.status(500).json({ success: false, message: 'No fue posible listar los gastos' });
  } finally {
    if (connection) await connection.close();
  }
});

app.post('/api/gastos', async (req, res) => {
  let connection;
  const { client_operation_id: operationId, user_id: userId, category_id: categoryId,
    amount, description, date, updated_at: updatedAt } = req.body;
  if (!operationId || !userId || !categoryId || !amount || !date || !updatedAt) {
    return res.status(400).json({ success: false, message: 'Faltan datos obligatorios del gasto' });
  }
  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });
    await ensureExpensesTable(connection);
    await connection.execute(`
      MERGE INTO CC_GASTOS_SYNC target
      USING (SELECT :operationId client_operation_id FROM dual) source
      ON (target.CLIENT_OPERATION_ID = source.client_operation_id)
      WHEN MATCHED THEN UPDATE SET
        target.USER_ID = :userId,
        target.CATEGORY_ID = :categoryId,
        target.AMOUNT = :amount,
        target.DESCRIPTION = :description,
        target.EXPENSE_DATE = :expenseDate,
        target.UPDATED_AT = :updatedAt
        WHERE target.UPDATED_AT < :updatedAt
      WHEN NOT MATCHED THEN INSERT
        (CLIENT_OPERATION_ID, USER_ID, CATEGORY_ID, AMOUNT, DESCRIPTION, EXPENSE_DATE, UPDATED_AT)
        VALUES (:operationId, :userId, :categoryId, :amount, :description,
          :expenseDate, :updatedAt)
    `, { operationId, userId: String(userId), categoryId: String(categoryId), amount,
      description: description || '', expenseDate: new Date(date), updatedAt: new Date(updatedAt) }, { autoCommit: true });
    const result = await connection.execute(
      `SELECT * FROM CC_GASTOS_SYNC WHERE CLIENT_OPERATION_ID = :operationId`,
      { operationId }, { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    res.status(200).json({ success: true, data: expenseFromRow(result.rows[0]) });
  } catch (error) {
    console.error('Error al sincronizar gasto:', error.message);
    res.status(500).json({ success: false, message: 'No fue posible sincronizar el gasto' });
  } finally {
    if (connection) await connection.close();
  }
});

app.get('/api/health', async (req, res) => {
  let connection;

  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });

    const result = await connection.execute(
      `SELECT 'CONNECTED' AS STATUS FROM DUAL`
    );

    res.status(200).json({
      success: true,
      message: 'API de CashControl funcionando correctamente',
      database: result.rows[0][0]
    });
  } catch (error) {
    console.error('Error de conexión con Oracle:', error.message);

    res.status(500).json({
      success: false,
      message: 'La API está funcionando, pero no fue posible conectar con Oracle'
    });
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (error) {
        console.error('Error al cerrar la conexión:', error.message);
      }
    }
  }
});

app.listen(PORT, () => {
  console.log(`Servidor CashControl ejecutándose en http://localhost:${PORT}`);
});